# Generated by Django 3.2.9 on 2021-12-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='from_message',
            new_name='from_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='to_message',
            new_name='to_id',
        ),
    ]
