# Generated by Django 3.2.9 on 2021-12-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default='08/12/2021 22:36:15'),
        ),
    ]
